"use strict";
const FEATURES={afqtAdaptive:true,givTutor:false,greTutor:false};
const LINKS={percentages:"https://www.khanacademy.org/math/pre-algebra/pre-algebra-ratios-rates/pre-algebra-percent-problems",fractions:"https://www.khanacademy.org/math/arithmetic/fraction-arithmetic",rates:"https://www.khanacademy.org/math/pre-algebra/pre-algebra-ratios-rates",geometry:"https://www.khanacademy.org/math/basic-geo/basic-geo-area-and-perimeter",algebra:"https://www.khanacademy.org/math/algebra",number_theory:"https://www.khanacademy.org/math/pre-algebra/pre-algebra-factors-multiples",vocab:"https://www.khanacademy.org/test-prep/sat/x0a8c2e5f:reading-and-writing-lessons/x0a8c2e5f:vocabulary",main_idea:"https://www.khanacademy.org/test-prep/sat/x0a8c2e5f:reading-and-writing-lessons"};
const BANK=[
{id:"WK1",area:"vocab",section:"WK",topic:"vocab",difficulty:"easy",stem:"Select the word closest in meaning to: BRAVE",choices:["Fearful","Courageous","Quiet","Careless"],answer:1,explanation:"Brave means courageous: willing to face danger or difficulty.",cue:"Dari/Farsi cue: brave = shoja / courageous."},
{id:"WK2",area:"vocab",section:"WK",topic:"vocab",difficulty:"easy",stem:"Select the word closest in meaning to: PURCHASE",choices:["Buy","Break","Carry","Lose"],answer:0,explanation:"To purchase something is to buy it.",cue:"Dari/Farsi cue: purchase = buy / kharidan."},
{id:"WK3",area:"vocab",section:"WK",topic:"vocab",difficulty:"easy",stem:"Select the word closest in meaning to: ASSIST",choices:["Help","Hide","Argue","Delay"],answer:0,explanation:"Assist means help."},
{id:"WK4",area:"vocab",section:"WK",topic:"vocab",difficulty:"medium",stem:"Select the word closest in meaning to: RELUCTANT",choices:["Unwilling","Excited","Certain","Generous"],answer:0,explanation:"Reluctant means unwilling or hesitant.",cue:"Dari/Farsi cue: reluctant = not willing / hesitant."},
{id:"WK5",area:"vocab",section:"WK",topic:"vocab",difficulty:"medium",stem:"The mechanic inspected the engine carefully before making a repair. In this sentence, inspected most nearly means:",choices:["Ignored","Examined","Removed","Painted"],answer:1,explanation:"Inspected means examined or looked at carefully."},
{id:"WK6",area:"vocab",section:"WK",topic:"vocab",difficulty:"hard",stem:"Select the word closest in meaning to: CONCISE",choices:["Brief","Confusing","Ancient","Weak"],answer:0,explanation:"Concise means brief but complete, with no extra words."},
{id:"WK7",area:"vocab",section:"WK",topic:"vocab",difficulty:"hard",stem:"Although the first plan failed, the team devised an alternate solution. Devised most nearly means:",choices:["Forgot","Created","Rejected","Measured"],answer:1,explanation:"Devised means created or came up with a plan."},
{id:"PC1",area:"vocab",section:"PC",topic:"main_idea",difficulty:"medium",stem:"Read the passage: The city added more buses during rush hour because many workers were arriving late. The change reduced crowding and helped people get to work on time. What is the main idea?",choices:["The city changed bus service to improve commuting","Workers stopped using buses","Rush hour was canceled","Buses are always empty"],answer:0,explanation:"The passage is about adding buses to improve commuting."},
{id:"AR1",area:"math",section:"AR",topic:"fractions",difficulty:"easy",stem:"A recipe uses 1/2 cup of oil for one batch. How much oil is needed for 4 batches?",choices:["1 cup","2 cups","3 cups","4 cups"],answer:1,explanation:"1/2 x 4 = 2 cups."},
{id:"AR2",area:"math",section:"AR",topic:"rates",difficulty:"easy",stem:"A car travels 60 miles in 1 hour. At the same speed, how far does it travel in 3 hours?",choices:["120 miles","150 miles","180 miles","240 miles"],answer:2,explanation:"60 x 3 = 180 miles."},
{id:"AR3",area:"math",section:"AR",topic:"percentages",difficulty:"medium",stem:"A jacket costs $80 and is 25% off. What is the sale price?",choices:["$20","$55","$60","$75"],answer:2,explanation:"25% of $80 is $20. $80 - $20 = $60."},
{id:"AR4",area:"math",section:"AR",topic:"rates",difficulty:"medium",stem:"A map scale is 1 inch = 20 miles. Two towns are 3.5 inches apart. How many miles apart are they?",choices:["35","50","60","70"],answer:3,explanation:"3.5 x 20 = 70 miles."},
{id:"AR5",area:"math",section:"AR",topic:"fractions",difficulty:"medium",stem:"A tank is 3/5 full and contains 48 gallons. How many gallons does the full tank hold?",choices:["60","72","80","96"],answer:2,explanation:"48 is 3/5 of the tank. Full tank = 48 x 5/3 = 80."},
{id:"AR6",area:"math",section:"AR",topic:"percentages",difficulty:"hard",stem:"A shirt costs $45 after a 10% discount. What was the original price?",choices:["$40.50","$49.50","$50","$55"],answer:2,explanation:"$45 is 90% of the original price. 45 / 0.90 = 50."},
{id:"MK1",area:"math",section:"MK",topic:"algebra",difficulty:"easy",stem:"Solve for x: x + 7 = 12",choices:["3","5","7","19"],answer:1,explanation:"Subtract 7 from both sides: x = 5."},
{id:"MK2",area:"math",section:"MK",topic:"geometry",difficulty:"easy",stem:"What is the area of a rectangle with length 8 and width 5?",choices:["13","26","40","80"],answer:2,explanation:"Area = length x width = 8 x 5 = 40."},
{id:"MK3",area:"math",section:"MK",topic:"algebra",difficulty:"medium",stem:"Simplify: 4(3x - 2) - 5x",choices:["7x - 8","12x - 8","7x - 2","7x + 8"],answer:0,explanation:"4(3x - 2)=12x-8; 12x-8-5x=7x-8."},
{id:"MK4",area:"math",section:"MK",topic:"number_theory",difficulty:"medium",stem:"What is the greatest common factor of 36 and 48?",choices:["6","9","12","18"],answer:2,explanation:"36 and 48 are both divisible by 12, and no larger common factor works."},
{id:"MK5",area:"math",section:"MK",topic:"geometry",difficulty:"hard",stem:"A right triangle has legs of 3 and 4. What is the hypotenuse?",choices:["5","6","7","12"],answer:0,explanation:"This is a 3-4-5 triangle. You can also use a squared plus b squared equals c squared: 9+16=25, so c=5."},
{id:"MK6",area:"math",section:"MK",topic:"algebra",difficulty:"hard",stem:"A line passes through (0, 2) and (3, 8). What is its slope?",choices:["2","3","4","6"],answer:0,explanation:"Slope = (8-2)/(3-0)=6/3=2."}
];
const $=id=>document.getElementById(id);let state={sessionId:null,startedAt:null,current:null,qStart:0,count:0,selected:null,locked:false,history:[],difficulty:"medium",focus:"mixed",studentName:"Student"};let tick=null;
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));}
function label(s){return String(s).replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase());}
function now(){return new Date().toISOString();}
function loadLocal(){try{return JSON.parse(localStorage.getItem("afqtAdaptiveHistory")||"[]");}catch{return[];}}
function saveLocal(){localStorage.setItem("afqtAdaptiveHistory",JSON.stringify(state.history.slice(-400)));}
function start(){state.sessionId="afqt-"+Date.now().toString(36);state.startedAt=now();state.history=loadLocal();state.difficulty=$("difficulty").value;state.focus=$("focus").value;state.studentName=$("studentName").value.trim()||"Student";state.count=0;$("setup").classList.add("hidden");$("practice").classList.remove("hidden");nextQuestion();renderStats();}
function pool(){let p=BANK.filter(q=>(state.focus==="mixed"||q.area===state.focus)&&q.difficulty===state.difficulty);if(!p.length)p=BANK.filter(q=>state.focus==="mixed"||q.area===state.focus);return p;}
function chooseQuestion(){const p=pool();const recent=state.history.slice(-8).map(a=>a.questionId);const fresh=p.filter(q=>!recent.includes(q.id));const arr=fresh.length?fresh:p;return arr[Math.floor(Math.random()*arr.length)];}
function nextQuestion(){state.current=chooseQuestion();state.qStart=Date.now();state.selected=null;state.locked=false;state.count++;$("qNum").textContent="Question "+state.count;$("qTopic").textContent=label(state.current.topic);$("qDiff").textContent=label(state.current.difficulty);$("progressFill").style.width=Math.min(100,state.count*5)+"%";$("stem").textContent=state.current.stem;renderCue();renderChoices();$("feedback").className="feedback hidden";$("feedback").textContent="";$("checkBtn").disabled=true;$("nextBtn").disabled=true;if(tick)clearInterval(tick);tick=setInterval(()=>$("timer").textContent=Math.round((Date.now()-state.qStart)/1000)+"s",250);}
function renderCue(){const box=$("languageHelp");if(state.current.cue){box.innerHTML="<strong>Dari/Farsi support:</strong> "+esc(state.current.cue);box.className="feedback warn";}else{box.className="feedback warn hidden";box.textContent="";}}
function renderChoices(){const c=$("choices");c.textContent="";state.current.choices.forEach((txt,i)=>{const b=document.createElement("button");b.className="choice";b.innerHTML="<div class='letter'>"+"ABCD"[i]+"</div><div class='text'>"+esc(txt)+"</div>";b.onclick=()=>select(i);c.appendChild(b);});}
function select(i){if(state.locked)return;state.selected=i;document.querySelectorAll(".choice").forEach((b,idx)=>b.classList.toggle("selected",idx===i));$("checkBtn").disabled=false;if($("feedbackMode").value==="instant")check();}
function check(){if(state.selected==null||state.locked)return;state.locked=true;if(tick)clearInterval(tick);const q=state.current;const correct=state.selected===q.answer;const durationMs=Date.now()-state.qStart;document.querySelectorAll(".choice").forEach((b,idx)=>{if(idx===q.answer)b.classList.add("correct");if(idx===state.selected&&!correct)b.classList.add("incorrect");});const attempt={sessionId:state.sessionId,studentName:state.studentName,timestamp:now(),questionId:q.id,area:q.area,section:q.section,topic:q.topic,difficulty:q.difficulty,stem:q.stem,choices:q.choices,studentAnswerIndex:state.selected,studentText:q.choices[state.selected],correctAnswerIndex:q.answer,correctText:q.choices[q.answer],correct,durationMs,explanation:q.explanation,khanLink:LINKS[q.topic]||"https://www.khanacademy.org/"};state.history.push(attempt);saveLocal();adapt();showFeedback(attempt);logAttempt(attempt);renderStats();$("checkBtn").disabled=true;$("nextBtn").disabled=false;}
function showFeedback(a){const f=$("feedback");f.className="feedback "+(a.correct?"good":"bad");f.innerHTML=(a.correct?"<strong>Correct.</strong> ":"<strong>Not quite.</strong> ")+esc(a.explanation)+"<div class='study'>Study link: <a target='_blank' rel='noopener' href='"+a.khanLink+"'>"+esc(label(a.topic))+" on Khan Academy</a></div>"+weaknessMessage(a.topic);}
function weaknessMessage(topic){const recent=state.history.filter(a=>a.topic===topic).slice(-5);if(recent.length<3)return"";const misses=recent.filter(a=>!a.correct).length;if(misses>=2)return"<p><strong>Flag:</strong> This concept is shaky. I will drop difficulty and show easier related questions.</p>";return"<p><strong>Trend:</strong> This concept is improving.</p>";}
function adapt(){const recent=state.history.slice(-5);const acc=recent.filter(a=>a.correct).length/(recent.length||1);const last=state.history[state.history.length-1];const topicRecent=state.history.filter(a=>a.topic===last.topic).slice(-4);const misses=topicRecent.filter(a=>!a.correct).length;if(topicRecent.length>=3&&misses>=2){state.difficulty="easy";return;}if(recent.length>=4&&acc>=.8&&state.difficulty==="easy")state.difficulty="medium";else if(recent.length>=4&&acc>=.8&&state.difficulty==="medium")state.difficulty="hard";else if(recent.length>=4&&acc<.5&&state.difficulty==="hard")state.difficulty="medium";else if(recent.length>=4&&acc<.5&&state.difficulty==="medium")state.difficulty="easy";}
function renderStats(){const saved=loadLocal();if(saved.length>state.history.length)state.history=saved;const total=state.history.length,correct=state.history.filter(a=>a.correct).length;$("summary").innerHTML="<div>Total attempts</div><strong>"+total+"</strong><div>Correct</div><strong>"+correct+"</strong><div>Accuracy</div><strong>"+(total?Math.round(correct/total*100)+"%":"--")+"</strong><div>Current difficulty</div><strong>"+esc(state.difficulty)+"</strong>";renderWeaknesses();renderHistory();}
function renderWeaknesses(){const map={};state.history.forEach(a=>{map[a.topic]??={n:0,c:0,ms:0};map[a.topic].n++;if(a.correct)map[a.topic].c++;map[a.topic].ms+=a.durationMs;});const rows=Object.entries(map).map(([topic,s])=>({topic,n:s.n,acc:s.c/s.n,avg:Math.round(s.ms/s.n/1000)})).sort((a,b)=>a.acc-b.acc||b.n-a.n).slice(0,6);$("weaknesses").innerHTML=rows.length?rows.map(r=>"<div class='topic-row'><strong>"+esc(label(r.topic))+"</strong> <span class='pill "+(r.acc<.6?"bad":r.acc<.8?"warn":"good")+"'>"+Math.round(r.acc*100)+"%</span><div class='tiny'>"+r.n+" attempts | avg "+r.avg+"s | <a target='_blank' href='"+(LINKS[r.topic]||"https://www.khanacademy.org/")+"'>study link</a></div></div>").join(""):"<p class='tiny'>Weaknesses will appear after a few questions.</p>";}
function renderHistory(){const h=state.history.slice(-20).reverse();$("history").innerHTML=h.length?h.map(a=>"<div class='hist-item'><strong>"+(a.correct?"OK":"MISS")+" "+esc(label(a.topic))+"</strong> | "+esc(a.difficulty)+" | "+Math.round(a.durationMs/1000)+"s<br>"+esc(new Date(a.timestamp).toLocaleString())+"<br>Answer: "+esc(a.studentText)+" -> "+esc(a.correctText)+"</div>").join(""):"No attempts yet.";}
function payloadFromAttempt(a){return{sessionKind:"AFQT_FREEPLAY_ATTEMPT",studentName:a.studentName,timestamp:a.timestamp,sessionType:"FREEPLAY",mode:"adaptive-freeplay",totalCorrect:a.correct?1:0,totalItems:1,adaptive:{sessionId:a.sessionId,topic:a.topic,difficulty:a.difficulty,durationMs:a.durationMs,khanLink:a.khanLink},sections:[{code:a.section,total:1,score:a.correct?1:0,difficulty:a.difficulty,questions:[{stem:a.stem,studentText:a.studentText,correctText:a.correctText,correct:a.correct,explanation:a.explanation,topic:a.topic,difficulty:a.difficulty,durationMs:a.durationMs,timestamp:a.timestamp,khanLink:a.khanLink}]}]};}
function logAttempt(a){const body=JSON.stringify(payloadFromAttempt(a));try{if(navigator.sendBeacon){navigator.sendBeacon("/api/log",new Blob([body],{type:"application/json"}));return;}}catch{}fetch("/api/log",{method:"POST",headers:{"Content-Type":"application/json"},body,keepalive:true}).catch(()=>{});}
function finish(){if(tick)clearInterval(tick);const h=state.history.filter(a=>a.sessionId===state.sessionId);const payload={sessionKind:"AFQT_ADAPTIVE_FREEPLAY",studentName:state.studentName,timestamp:now(),sessionType:"FREEPLAY",mode:"adaptive-freeplay",totalCorrect:h.filter(a=>a.correct).length,totalItems:h.length,adaptive:{sessionId:state.sessionId,featureFlags:FEATURES,weakTopics:topWeak(h)},sections:[{code:"AFQT",total:h.length,score:h.filter(a=>a.correct).length,difficulty:"adaptive",questions:h.map(a=>({stem:a.stem,studentText:a.studentText,correctText:a.correctText,correct:a.correct,explanation:a.explanation,topic:a.topic,difficulty:a.difficulty,durationMs:a.durationMs,timestamp:a.timestamp,khanLink:a.khanLink}))}]};fetch("/api/log",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}).finally(()=>alert("Session synced. Open /api/sessions?key=tutor to view it."));}
function topWeak(items){const m={};items.forEach(a=>{m[a.topic]??={n:0,c:0};m[a.topic].n++;if(a.correct)m[a.topic].c++;});return Object.entries(m).map(([topic,s])=>({topic,accuracy:s.c/s.n,attempts:s.n})).sort((a,b)=>a.accuracy-b.accuracy).slice(0,5);}
$("startBtn").onclick=start;$("checkBtn").onclick=check;$("nextBtn").onclick=nextQuestion;$("finishBtn").onclick=finish;$("resetBtn").onclick=()=>{if(confirm("Clear local attempt history on this device?")){localStorage.removeItem("afqtAdaptiveHistory");state.history=[];renderStats();}};document.addEventListener("keydown",e=>{const k=e.key.toLowerCase();if("abcd".includes(k)&&!$("practice").classList.contains("hidden"))select("abcd".indexOf(k));if(k==="enter"&&!$("nextBtn").disabled)nextQuestion();});state.history=loadLocal();renderStats();
